sonar.projectKey=howzy-backend-api
sonar.projectName=Howzy Backend API
sonar.projectVersion=1.0

sonar.sources=src
sonar.exclusions=**/node_modules/**,**/lib/**,**/*.test.ts,**/*.spec.ts

sonar.typescript.lcov.reportPaths=coverage/lcov.info

sonar.sourceEncoding=UTF-8
