extend type Mutation {
  """
  ✨ Insert a single `Configuration` into the table and return its key. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  configuration_insert(
    """
    Data object to insert into the table.
    """
    data: Configuration_Data!
  ): Configuration_KeyOutput! @fdc_generated(from: "Configuration", purpose: INSERT_SINGLE)
  """
  ✨ Insert a single `Project` into the table and return its key. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  project_insert(
    """
    Data object to insert into the table.
    """
    data: Project_Data!
  ): Project_KeyOutput! @fdc_generated(from: "Project", purpose: INSERT_SINGLE)
  """
  ✨ Insert a single `ProjectAmenity` into the table and return its key. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  projectAmenity_insert(
    """
    Data object to insert into the table.
    """
    data: ProjectAmenity_Data!
  ): ProjectAmenity_KeyOutput! @fdc_generated(from: "ProjectAmenity", purpose: INSERT_SINGLE)
  """
  ✨ Insert a single `ProjectPhoto` into the table and return its key. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  projectPhoto_insert(
    """
    Data object to insert into the table.
    """
    data: ProjectPhoto_Data!
  ): ProjectPhoto_KeyOutput! @fdc_generated(from: "ProjectPhoto", purpose: INSERT_SINGLE)
  """
  ✨ Insert `Configuration` objects into the table and return their keys. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  configuration_insertMany(
    """
    List of data objects to insert into the table.
    """
    data: [Configuration_Data!]!
  ): [Configuration_KeyOutput!]! @fdc_generated(from: "Configuration", purpose: INSERT_MULTIPLE)
  """
  ✨ Insert `Project` objects into the table and return their keys. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  project_insertMany(
    """
    List of data objects to insert into the table.
    """
    data: [Project_Data!]!
  ): [Project_KeyOutput!]! @fdc_generated(from: "Project", purpose: INSERT_MULTIPLE)
  """
  ✨ Insert `ProjectAmenity` objects into the table and return their keys. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  projectAmenity_insertMany(
    """
    List of data objects to insert into the table.
    """
    data: [ProjectAmenity_Data!]!
  ): [ProjectAmenity_KeyOutput!]! @fdc_generated(from: "ProjectAmenity", purpose: INSERT_MULTIPLE)
  """
  ✨ Insert `ProjectPhoto` objects into the table and return their keys. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  projectPhoto_insertMany(
    """
    List of data objects to insert into the table.
    """
    data: [ProjectPhoto_Data!]!
  ): [ProjectPhoto_KeyOutput!]! @fdc_generated(from: "ProjectPhoto", purpose: INSERT_MULTIPLE)
  """
  ✨ Insert or update a single `Configuration` into the table, based on the primary key. Returns the key of the newly inserted or existing updated `Configuration`.
  """
  configuration_upsert(
    """
    Data object to insert or update if it already exists.
    """
    data: Configuration_Data!
  ): Configuration_KeyOutput! @fdc_generated(from: "Configuration", purpose: UPSERT_SINGLE)
  """
  ✨ Insert or update a single `Project` into the table, based on the primary key. Returns the key of the newly inserted or existing updated `Project`.
  """
  project_upsert(
    """
    Data object to insert or update if it already exists.
    """
    data: Project_Data!
  ): Project_KeyOutput! @fdc_generated(from: "Project", purpose: UPSERT_SINGLE)
  """
  ✨ Insert or update a single `ProjectAmenity` into the table, based on the primary key. Returns the key of the newly inserted or existing updated `ProjectAmenity`.
  """
  projectAmenity_upsert(
    """
    Data object to insert or update if it already exists.
    """
    data: ProjectAmenity_Data!
  ): ProjectAmenity_KeyOutput! @fdc_generated(from: "ProjectAmenity", purpose: UPSERT_SINGLE)
  """
  ✨ Insert or update a single `ProjectPhoto` into the table, based on the primary key. Returns the key of the newly inserted or existing updated `ProjectPhoto`.
  """
  projectPhoto_upsert(
    """
    Data object to insert or update if it already exists.
    """
    data: ProjectPhoto_Data!
  ): ProjectPhoto_KeyOutput! @fdc_generated(from: "ProjectPhoto", purpose: UPSERT_SINGLE)
  """
  ✨ Insert or update `Configuration` objects into the table, based on the primary key. Returns the key of the newly inserted or existing updated `Configuration`.
  """
  configuration_upsertMany(
    """
    List of data objects to insert or update if it already exists.
    """
    data: [Configuration_Data!]!
  ): [Configuration_KeyOutput!]! @fdc_generated(from: "Configuration", purpose: UPSERT_MULTIPLE)
  """
  ✨ Insert or update `Project` objects into the table, based on the primary key. Returns the key of the newly inserted or existing updated `Project`.
  """
  project_upsertMany(
    """
    List of data objects to insert or update if it already exists.
    """
    data: [Project_Data!]!
  ): [Project_KeyOutput!]! @fdc_generated(from: "Project", purpose: UPSERT_MULTIPLE)
  """
  ✨ Insert or update `ProjectAmenity` objects into the table, based on the primary key. Returns the key of the newly inserted or existing updated `ProjectAmenity`.
  """
  projectAmenity_upsertMany(
    """
    List of data objects to insert or update if it already exists.
    """
    data: [ProjectAmenity_Data!]!
  ): [ProjectAmenity_KeyOutput!]! @fdc_generated(from: "ProjectAmenity", purpose: UPSERT_MULTIPLE)
  """
  ✨ Insert or update `ProjectPhoto` objects into the table, based on the primary key. Returns the key of the newly inserted or existing updated `ProjectPhoto`.
  """
  projectPhoto_upsertMany(
    """
    List of data objects to insert or update if it already exists.
    """
    data: [ProjectPhoto_Data!]!
  ): [ProjectPhoto_KeyOutput!]! @fdc_generated(from: "ProjectPhoto", purpose: UPSERT_MULTIPLE)
  """
  ✨ Update a single `Configuration` based on `id`, `key` or `first`, setting columns specified in `data`. Returns the key of the updated `Configuration` or `null` if not found.
  """
  configuration_update(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: Configuration_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: Configuration_FirstRow

    """
    Data object containing fields to be updated.
    """
    data: Configuration_Data!
  ): Configuration_KeyOutput @fdc_generated(from: "Configuration", purpose: UPDATE_SINGLE)
  """
  ✨ Update a single `Project` based on `id`, `key` or `first`, setting columns specified in `data`. Returns the key of the updated `Project` or `null` if not found.
  """
  project_update(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: Project_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: Project_FirstRow

    """
    Data object containing fields to be updated.
    """
    data: Project_Data!
  ): Project_KeyOutput @fdc_generated(from: "Project", purpose: UPDATE_SINGLE)
  """
  ✨ Update a single `ProjectAmenity` based on `id`, `key` or `first`, setting columns specified in `data`. Returns the key of the updated `ProjectAmenity` or `null` if not found.
  """
  projectAmenity_update(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: ProjectAmenity_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: ProjectAmenity_FirstRow

    """
    Data object containing fields to be updated.
    """
    data: ProjectAmenity_Data!
  ): ProjectAmenity_KeyOutput @fdc_generated(from: "ProjectAmenity", purpose: UPDATE_SINGLE)
  """
  ✨ Update a single `ProjectPhoto` based on `id`, `key` or `first`, setting columns specified in `data`. Returns the key of the updated `ProjectPhoto` or `null` if not found.
  """
  projectPhoto_update(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: ProjectPhoto_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: ProjectPhoto_FirstRow

    """
    Data object containing fields to be updated.
    """
    data: ProjectPhoto_Data!
  ): ProjectPhoto_KeyOutput @fdc_generated(from: "ProjectPhoto", purpose: UPDATE_SINGLE)
  """
  ✨ Update `Configuration` objects matching `where` conditions (or `all`, if true) according to `data`. Returns the number of rows updated.
  """
  configuration_updateMany(
    """
    Filter condition to specify which rows to update.
    """
    where: Configuration_Filter

    """
    Set to true to update all rows.
    """
    all: Boolean = false

    """
    Data object containing fields to update.
    """
    data: Configuration_Data!
  ): Int! @fdc_generated(from: "Configuration", purpose: UPDATE_MULTIPLE)
  """
  ✨ Update `Project` objects matching `where` conditions (or `all`, if true) according to `data`. Returns the number of rows updated.
  """
  project_updateMany(
    """
    Filter condition to specify which rows to update.
    """
    where: Project_Filter

    """
    Set to true to update all rows.
    """
    all: Boolean = false

    """
    Data object containing fields to update.
    """
    data: Project_Data!
  ): Int! @fdc_generated(from: "Project", purpose: UPDATE_MULTIPLE)
  """
  ✨ Update `ProjectAmenity` objects matching `where` conditions (or `all`, if true) according to `data`. Returns the number of rows updated.
  """
  projectAmenity_updateMany(
    """
    Filter condition to specify which rows to update.
    """
    where: ProjectAmenity_Filter

    """
    Set to true to update all rows.
    """
    all: Boolean = false

    """
    Data object containing fields to update.
    """
    data: ProjectAmenity_Data!
  ): Int! @fdc_generated(from: "ProjectAmenity", purpose: UPDATE_MULTIPLE)
  """
  ✨ Update `ProjectPhoto` objects matching `where` conditions (or `all`, if true) according to `data`. Returns the number of rows updated.
  """
  projectPhoto_updateMany(
    """
    Filter condition to specify which rows to update.
    """
    where: ProjectPhoto_Filter

    """
    Set to true to update all rows.
    """
    all: Boolean = false

    """
    Data object containing fields to update.
    """
    data: ProjectPhoto_Data!
  ): Int! @fdc_generated(from: "ProjectPhoto", purpose: UPDATE_MULTIPLE)
  """
  ✨ Delete a single `Configuration` based on `id`, `key` or `first` and return its key (or `null` if not found).
  """
  configuration_delete(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: Configuration_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: Configuration_FirstRow
  ): Configuration_KeyOutput @fdc_generated(from: "Configuration", purpose: DELETE_SINGLE)
  """
  ✨ Delete a single `Project` based on `id`, `key` or `first` and return its key (or `null` if not found).
  """
  project_delete(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: Project_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: Project_FirstRow
  ): Project_KeyOutput @fdc_generated(from: "Project", purpose: DELETE_SINGLE)
  """
  ✨ Delete a single `ProjectAmenity` based on `id`, `key` or `first` and return its key (or `null` if not found).
  """
  projectAmenity_delete(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: ProjectAmenity_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: ProjectAmenity_FirstRow
  ): ProjectAmenity_KeyOutput @fdc_generated(from: "ProjectAmenity", purpose: DELETE_SINGLE)
  """
  ✨ Delete a single `ProjectPhoto` based on `id`, `key` or `first` and return its key (or `null` if not found).
  """
  projectPhoto_delete(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: ProjectPhoto_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: ProjectPhoto_FirstRow
  ): ProjectPhoto_KeyOutput @fdc_generated(from: "ProjectPhoto", purpose: DELETE_SINGLE)
  """
  ✨ Delete `Configuration` objects matching `where` conditions (or `all`, if true). Returns the number of rows deleted.
  """
  configuration_deleteMany(
    """
    Filter condition to specify which rows to delete.
    """
    where: Configuration_Filter

    """
    Set to true to delete all rows.
    """
    all: Boolean = false
  ): Int! @fdc_generated(from: "Configuration", purpose: DELETE_MULTIPLE)
  """
  ✨ Delete `Project` objects matching `where` conditions (or `all`, if true). Returns the number of rows deleted.
  """
  project_deleteMany(
    """
    Filter condition to specify which rows to delete.
    """
    where: Project_Filter

    """
    Set to true to delete all rows.
    """
    all: Boolean = false
  ): Int! @fdc_generated(from: "Project", purpose: DELETE_MULTIPLE)
  """
  ✨ Delete `ProjectAmenity` objects matching `where` conditions (or `all`, if true). Returns the number of rows deleted.
  """
  projectAmenity_deleteMany(
    """
    Filter condition to specify which rows to delete.
    """
    where: ProjectAmenity_Filter

    """
    Set to true to delete all rows.
    """
    all: Boolean = false
  ): Int! @fdc_generated(from: "ProjectAmenity", purpose: DELETE_MULTIPLE)
  """
  ✨ Delete `ProjectPhoto` objects matching `where` conditions (or `all`, if true). Returns the number of rows deleted.
  """
  projectPhoto_deleteMany(
    """
    Filter condition to specify which rows to delete.
    """
    where: ProjectPhoto_Filter

    """
    Set to true to delete all rows.
    """
    all: Boolean = false
  ): Int! @fdc_generated(from: "ProjectPhoto", purpose: DELETE_MULTIPLE)
}
