extend type Query {
  """
  ✨ Look up a single `Configuration` based on `id`, `key` or `first` and return selected fields (or `null` if not found).
  """
  configuration(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: Configuration_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: Configuration_FirstRow
  ): Configuration @fdc_generated(from: "Configuration", purpose: QUERY_SINGLE)
  """
  ✨ Look up a single `Project` based on `id`, `key` or `first` and return selected fields (or `null` if not found).
  """
  project(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: Project_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: Project_FirstRow
  ): Project @fdc_generated(from: "Project", purpose: QUERY_SINGLE)
  """
  ✨ Look up a single `ProjectAmenity` based on `id`, `key` or `first` and return selected fields (or `null` if not found).
  """
  projectAmenity(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: ProjectAmenity_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: ProjectAmenity_FirstRow
  ): ProjectAmenity @fdc_generated(from: "ProjectAmenity", purpose: QUERY_SINGLE)
  """
  ✨ Look up a single `ProjectPhoto` based on `id`, `key` or `first` and return selected fields (or `null` if not found).
  """
  projectPhoto(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: ProjectPhoto_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: ProjectPhoto_FirstRow
  ): ProjectPhoto @fdc_generated(from: "ProjectPhoto", purpose: QUERY_SINGLE)
  """
  ✨ List `Configuration` objects in the table and return selected fields, optionally filtered by `where` conditions
  """
  configurations(
    """
    Filter condition to narrow down the query results.
    """
    where: Configuration_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [Configuration_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100

    """
    Set to true to return distinct results.
    """
    distinct: Boolean = false

    """
    Filter condition to apply to the groups of aggregate queries.
    """
    having: Configuration_Having
  ): [Configuration!]! @fdc_generated(from: "Configuration", purpose: QUERY_MULTIPLE)
  """
  ✨ List `Project` objects in the table and return selected fields, optionally filtered by `where` conditions
  """
  projects(
    """
    Filter condition to narrow down the query results.
    """
    where: Project_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [Project_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100

    """
    Set to true to return distinct results.
    """
    distinct: Boolean = false

    """
    Filter condition to apply to the groups of aggregate queries.
    """
    having: Project_Having
  ): [Project!]! @fdc_generated(from: "Project", purpose: QUERY_MULTIPLE)
  """
  ✨ List `ProjectAmenity` objects in the table and return selected fields, optionally filtered by `where` conditions
  """
  projectAmenities(
    """
    Filter condition to narrow down the query results.
    """
    where: ProjectAmenity_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [ProjectAmenity_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100

    """
    Set to true to return distinct results.
    """
    distinct: Boolean = false

    """
    Filter condition to apply to the groups of aggregate queries.
    """
    having: ProjectAmenity_Having
  ): [ProjectAmenity!]! @fdc_generated(from: "ProjectAmenity", purpose: QUERY_MULTIPLE)
  """
  ✨ List `ProjectPhoto` objects in the table and return selected fields, optionally filtered by `where` conditions
  """
  projectPhotos(
    """
    Filter condition to narrow down the query results.
    """
    where: ProjectPhoto_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [ProjectPhoto_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100

    """
    Set to true to return distinct results.
    """
    distinct: Boolean = false

    """
    Filter condition to apply to the groups of aggregate queries.
    """
    having: ProjectPhoto_Having
  ): [ProjectPhoto!]! @fdc_generated(from: "ProjectPhoto", purpose: QUERY_MULTIPLE)
}
